baseURL = "https://yeltahir.com/"
defaultContentLanguage = "en"

theme = "LoveIt"
title = "Yass"


enableRobotsTXT = true


[params]
  version = "0.2.X"
  description = "My personal blog"
  defaultTheme = "black"
  dateFormat = "2006-01-02"




# Home page config
[params.home]
#  amount of RSS pages
rss = 10

    # Header title config
    [params.header.title]
        pre = "<i class='fab fa-hubspot'></i>"
        name = "Yass"
        typeit = true

    # TypeIt config
    [params.typeit]
        # typing speed between each step (measured in milliseconds)
        speed = 1
        # blinking speed of the cursor (measured in milliseconds)
        cursorSpeed = 1000
        # character used for the cursor (HTML format is supported)
        cursorChar = "|"
        # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
        duration = -1

    [params.home.profile]
          enable = true
          avatarURL = "/images/avatar.png"
          social = true
          subtitle = "Mildly interesting tidbits"
          disclaimer = "Data, Technology, Jazz"

    [params.social]
        GitHub = "https://github.com/diabolical-ninja"
        Linkedin = "yassineltahir/"

    # Footer config
    [params.footer]
        enable = true
        # LoveIt NEW | 0.2.0 Custom content (HTML format is supported)
        custom = ''
        # LoveIt NEW | 0.2.0 whether to show Hugo and theme info
        hugo = true
        # LoveIt NEW | 0.2.0 whether to show copyright info
        copyright = true
        # LoveIt NEW | 0.2.0 whether to show the author
        author = true
        # Site creation time
        since = 2020
        # license info (HTML format is supported)
        license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[author]
  name = "Yass"


[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = "<i class='fas fa-book'></i>"
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "cookbook"
    pre = "<i class='fas fa-cookie-bite'></i>"
    post = ""
    name = "Cookbook"
    url = "/cookbook/cookbook"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "github"
    pre = "<i class='fab fa-github fa-fw'></i>"
    post = ""
    name = ""
    url = "https://github.com/diabolical-ninja"
    title = "GitHub"
    weight = 6
  [[menu.main]]
    identifier = "about"
    pre = "<i class='far fa-address-card'></i>"
    post = ""
    name = "About"
    url = "/about/"
    title = ""
    weight = 5

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4




[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.search]
  enable = true
  type = "lunr"
  contentLength = 4000
  placeholder = ""
  maxResultLength = 10
  snippetLength = 30
  highlightTag = "em"
  absoluteURL = false
